const About = () => {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vel quam elementum pulvinar etiam non. Enim facilisis gravida neque convallis a cras. Viverra maecenas accumsan lacus vel facilisis volutpat est. Risus in hendrerit gravida rutrum quisque non tellus orci. Ac tincidunt vitae semper quis lectus nulla. Dolor sit amet consectetur adipiscing elit. Nunc consequat interdum varius sit amet. Tincidunt arcu non sodales neque sodales ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Nunc id cursus metus aliquam eleifend mi in. Fringilla ut morbi tincidunt augue interdum. Sagittis vitae et leo duis ut. Suspendisse interdum consectetur libero id faucibus. Eget magna fermentum iaculis eu non diam phasellus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vel quam elementum pulvinar etiam non. Enim facilisis gravida neque convallis a cras. Viverra maecenas accumsan lacus vel facilisis volutpat est. Risus in hendrerit gravida rutrum quisque non tellus orci. Ac tincidunt vitae semper quis lectus nulla. Dolor sit amet consectetur adipiscing elit. Nunc consequat interdum varius sit amet. Tincidunt arcu non sodales neque sodales ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Nunc id cursus metus aliquam eleifend mi in. Fringilla ut morbi tincidunt augue interdum. Sagittis vitae et leo duis ut. Suspendisse interdum consectetur libero id faucibus. Eget magna fermentum iaculis eu non diam phasellus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vel quam elementum pulvinar etiam non. Enim facilisis gravida neque convallis a cras. Viverra maecenas accumsan lacus vel facilisis volutpat est. Risus in hendrerit gravida rutrum quisque non tellus orci. Ac tincidunt vitae semper quis lectus nulla. Dolor sit amet consectetur adipiscing elit. Nunc consequat interdum varius sit amet. Tincidunt arcu non sodales neque sodales ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Nunc id cursus metus aliquam eleifend mi in. Fringilla ut morbi tincidunt augue interdum. Sagittis vitae et leo duis ut. Suspendisse interdum consectetur libero id faucibus. Eget magna fermentum iaculis eu non diam phasellus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vel quam elementum pulvinar etiam non. Enim facilisis gravida neque convallis a cras. Viverra maecenas accumsan lacus vel facilisis volutpat est. Risus in hendrerit gravida rutrum quisque non tellus orci. Ac tincidunt vitae semper quis lectus nulla. Dolor sit amet consectetur adipiscing elit. Nunc consequat interdum varius sit amet. Tincidunt arcu non sodales neque sodales ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Nunc id cursus metus aliquam eleifend mi in. Fringilla ut morbi tincidunt augue interdum. Sagittis vitae et leo duis ut. Suspendisse interdum consectetur libero id faucibus. Eget magna fermentum iaculis eu non diam phasellus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vel quam elementum pulvinar etiam non. Enim facilisis gravida neque convallis a cras. Viverra maecenas accumsan lacus vel facilisis volutpat est. Risus in hendrerit gravida rutrum quisque non tellus orci. Ac tincidunt vitae semper quis lectus nulla. Dolor sit amet consectetur adipiscing elit. Nunc consequat interdum varius sit amet. Tincidunt arcu non sodales neque sodales ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Nunc id cursus metus aliquam eleifend mi in. Fringilla ut morbi tincidunt augue interdum. Sagittis vitae et leo duis ut. Suspendisse interdum consectetur libero id faucibus. Eget magna fermentum iaculis eu non diam phasellus.</p>
    </div>
  );
}

export default About;